Class ObjectScript.Example
{
ClassMethod HelloWolrld() As %Status
{
    Write "Hello" /* test */
    Return $$$OK
    s codeB="1 первая тут были новые новая строка"
    s codeB="2 вторая тут были новые новая строка"
    s codeB="3 третья тут были новые новая строка"
}
ClassMethod HelloWolrld_1() As %Status
{
    Write "Hello" /* test */
    Return $$$OK
    s codeB="1 первая тут были новые новая строка"
    s codeB="2 вторая тут были новые новая строка"
    s codeB="3 третья тут были новые новая строка"
}
ClassMethod HelloWolrld_2() As %Status
{
    Write "Hello" /* test 2*/
    Return $$$OK
    s codeB="1 первая тут были новые новая строка"
    s codeB="2 вторая тут были новые новая строка"
    s codeB="3 третья тут были новые новая строка"
}
