Class ObjectScript.Example
{
ClassMethod HelloWolrld() As %Status
{
    Write "Hello" /* test */
    Return $$$OK
    s codeB="1 первая тут были новые новая строка"
    s codeB="2 вторая тут были новые новая строка"
    s codeB="3 третья тут были новые новая строка"
}
ClassMethod HelloWolrld1() As %Status
{
    Write "Hello" /* test */
    Return $$$OK
    s codeB="1 первая тут были новые новая строка"
    s codeB="2 вторая тут были новые новая строка"
    s codeB="3 третья тут были новые новая строка"
kmbbv
}